### ISSUE TITLE
OAuth and remote redirect using forge:///

### ISSUE THREAD

**Issue by NathanWalker** [trigger-corp/trigger.io-tabs#3]
I'm trying to fix what appears to be a bug in iOS 7 when using OAuth as described in this doc:
https://trigger.io/docs/current/recipes/integrations/modal.html

We control our server so I was able to do the `Remote Redirect` to `forge:///index.html`, however this fails everytime with:

```
[WARNING] Modal webview error: Error Domain=WebKitErrorDomain Code=102 "Frame load interrupted" UserInfo=0xccd5b10 {NSErrorFailingURLKey=forge:///index.html#!/login?token=d19a34cc-5ac8-4c27-81d5-4f9e2ad07717&id=2&url=%2F&provider=google_oauth2&new_user=false, NSErrorFailingURLStringKey=forge:///index.html#!/login?token=d19a34cc-5ac8-4c27-81d5-4f9e2ad07717&id=2&url=%2F&provider=google_oauth2&new_user=false, NSLocalizedDescription=Frame load interrupted}
[DEBUG] Returned to javascript: {
[DEBUG]     event = "tabs.F4F10236-A349-4E6D-A2B0-CED20DD0FFAC.loadError";
[DEBUG]     params =     {
[DEBUG]         description = "Error Domain=WebKitErrorDomain Code=102 \"Frame load interrupted\" UserInfo=0xccd5b10 {NSErrorFailingURLKey=forge:///index.html#!/login?token=d19a34cc-5ac8-4c27-81d5-4f9e2ad07717&id=2&url=%2F&provider=google_oauth2&new_user=false, NSErrorFailingURLStringKey=forge:///index.html#!/login?token=d19a34cc-5ac8-4c27-81d5-4f9e2ad07717&id=2&url=%2F&provider=google_oauth2&new_user=false, NSLocalizedDescription=Frame load interrupted}";
[DEBUG]         url = "";
[DEBUG]     };
[DEBUG] }
[DEBUG] 2013-12-06 19:01:21.755 Forge[38282:80b] Warning: Attempt to dismiss from view controller <ForgeViewController: 0xcc711a0> while a presentation or dismiss is in progress!
[DEBUG] Returned to javascript: {
[DEBUG]     event = "tabs.F4F10236-A349-4E6D-A2B0-CED20DD0FFAC.closed";
[DEBUG]     params =     {
[DEBUG]     };
[DEBUG] }

```

I did some research and I think it may be related to these issues:
http://stackoverflow.com/questions/4299403/how-to-handle-app-urls-in-a-uiwebview

http://stackoverflow.com/questions/19713610/how-to-resolve-frame-load-interrupted-error-in-uiwebview

http://stackoverflow.com/questions/1482736/frame-load-interrupted-error-while-loading-a-word-document-in-uiwebview

http://stackoverflow.com/questions/16073519/nsurlerrordomain-error-code-999-in-ios

Can anyone help shed some light on this issue for me?

**Comment by antoinevg** [comment]
The use of tabs to do OAuth has been superseded by: https://github.com/trigger-corp/trigger.io-oauth
