### ISSUE TITLE
Android multiple file upload

### ISSUE THREAD

**Issue by FenziRocks** [trigger-corp/trigger.io-tabs#30]
We have been faced an issue with Android and standard multi file upload.

IOS: is working, with multiple files

Android: is working, but just for 1 file.
Version: Android 9

### Actual behavior
- https://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_input_multiple
- take this simple multi upload and use it on an Android with the tabs module

### Result
- Just one file can be selected on Android

*The question is could this be fixed by you?*

**Comment by antoinevg** [comment]
The Android web view only started supporting multiple file selections as of Chrome 79 in December of last year:

https://caniuse.com/#feat=input-file-multiple

One way you could workaround this is to create your own custom file picker in native code. 

Here's an example of how we once did something similar for date pickers:

https://trigger.io/modules/ui/current/docs/index.html

First, we have javascript wrappers that redirect the handling of the <input> elements to our own forge calls:

https://github.com/trigger-corp/trigger.io-ui/blob/master/module/javascript/module.js

Then we implemented the replacement UI's in native code:

https://github.com/trigger-corp/trigger.io-ui/blob/master/inspector/an-inspector/ForgeModule/src/io/trigger/forge/android/modules/ui/API.java

**Comment by FenziRocks** [comment]
Thank you very much.
